build: 'off'

install:
  - ps: 'Install-Product node 5 x64'
  - npm install --global npm-windows-upgrade
  - npm-windows-upgrade --no-spinner --npm-version latest
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
