build: 'off'

cache:
  - node_modules
  #- app\node_modules
  #- '%APPDATA%\npm-cache'
  #- '%USERPROFILE%\.electron'

install:
  - ps: 'Install-Product node 6 x64'
 # - npm install --global npm-windows-upgrade
 # - npm-windows-upgrade --no-spinner --npm-version latest
 # - npm install
  
  - npm install npm -g
  - appveyor-retry npm prune
  - npm update
  
#test_script:
#  - node --version
#  - npm --version
#  - npm test

on_finish:
   - 7z a logs.zip C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\
   - appveyor PushArtifact logs.zip
